# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_spatialresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialresource',
            options={'ordering': ('name',)},
        ),
    ]
