# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20160927_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='hint',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
