# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20160927_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
